services:
  server:
    build: ./server
    image: karouma-o-carry-server
    container_name: karouma-server
    ports:
      - "5002:5002"
    env_file:
      - ./server/.env
    environment:
      PORT: 5002
    restart: unless-stopped
